### PR TITLE
Delete the witc dependency.

### PR DESCRIPTION
**Pull request by yanghaku**
This PR deletes the ```witc``` dependency when building.

1. delete the `build.rs`.
2. add the script to regenerate bindings when `.wit` is updated.
3. change ```MatKey``` to public.

### CODE REVIEW

**Comment by hydai** [comment]
Hi @yanghaku 
What's the reason for removing the `witc` dependency? And is it a best practice to add `generated.rs` into the source tree instead of building it from a spec file?

**Comment by dannypsnl** [comment]
1. delete the `build.sh` is wrong, you delete `build.rs`
2. we might out of sync from wit definition in this setup, what's the benefit?
3. this one is correct

**Comment by yanghaku** [comment]
Hello @hydai The reasons are as follows:
1. When using the crate `opencvmini`, I need to download the source code of `witc` and the Haskell toolchain to build `witc`. I think it's very inconvenient for Rust developers. And you can see the build error logs in the [docs.rs](https://docs.rs/crate/opencvmini/0.1.0/builds/874051). One of the solutions can be to add the function of installing `witc` in `build.rs`, and let this process be automated. But this increases the complexity. So I think it is better to remove the dependency of `witc`.
2. When the spec file is updated, its corresponding high-level wrap APIs in ```src/lib.rs``` also need to be updated, so a new version needs to be released on `crates.io`. It makes no sense to generate ```generated.rs``` when building, it is better to put it directly in the source tree.

**Comment by yanghaku** [comment]
Hi @dannypsnl I made a typo, I should have written ```build.rs```. 
By the way, how to get the raw byte data from Mat and use raw byte data to create a Mat using ```opencvmini```?

**Comment by dannypsnl** [comment]
imencode, imdecode

Unless you’re talking about bytes of opencv C++ struct, that would be impossible by design, unless you can tell the inevitable use case

**Comment by dannypsnl** [comment]
I would accept an installer in build.rs, out of sync shouldn’t be allowed

**Comment by yanghaku** [comment]
Does `imencode` can get image raw RGB byte data from Mat? I want to get image RGB data from Mat.

> imencode, imdecode
> 
> Unless you’re talking about bytes of opencv C++ struct, that would be impossible by design, unless you can tell the inevitable use case

**Comment by yanghaku** [comment]
Why installing the `witc` and Haskell toolchain in `build.rs` is better than adding generated code in the source tree?

Execute the script `scripts/regenerate-bindings-from-wit.sh` before publishing the library to `crates.io`, it will not be out of sync.

> I would accept an installer in build.rs, out of sync shouldn’t be allowed

**Comment by dannypsnl** [comment]
> Does `imencode` can get image raw RGB byte data from Mat? I want to get image RGB data from Mat.

Then the answer is yes, each pixel will contain RGB value

**Comment by dannypsnl** [comment]
> Execute the script scripts/regenerate-bindings-from-wit.sh before publishing the library to crates.io, it will not be out of sync.

Because this is a wrong assumption for what's out of sync.

If one update `.wit` definition and didn't update the generated file, it's possible to have a new type for same definition and didn't get implementation, it's also possible to uncheck that when we port more functions from OpenCV. If that happened, we will have to fix every mismatched things for release, that's a huge impact for maintainers.

As you told, install `witc` in `build.rs` can solve both problem, then that's the solution I will accept.

**Comment by yanghaku** [comment]
When `.wit` updates, should the high-level wrap APIs in `src/lib.rs` need to update? how to deal with this out-of-sync?

**Comment by dannypsnl** [comment]
No solution for `lib.rs` right now, but existed definitions will not mismatch since it will not compile.

The final target is generating all include high-level wrapper via `witc`, at that time we will no need these burden. However, WIT language is still developing, I have no recent plan for it.

**Comment by yanghaku** [comment]
Generating `generated.rs` and `lib.rs` in build time can not solve wit version problem.
For example, if `.wit` has two versions: wit_v1, wit_v2
* wit_v1 ->  published `opencvmini` crate version v0.1.0 (contains  [wit_v1](https://docs.rs/crate/opencvmini/latest/source/wasmedge_opencvmini.wit), generated.rs_v1, lib.rs_v1)
* wit_v2 ->  published `opencvmini` crate version v0.2.0 (contains  wit_v2, generated.rs_v2, lib.rs_v2)

When I use the  `opencvmini` crate version v0.1.0, I still can use the old version wit_v1 definition to build a rust program.

---
And I don't understand if the discussion above has anything to do with this PR.

If the `.wit` file updates:
1. Publish the new version `.wit` to `crates.io`, then users generate this version  `generated.rs` (and `lib.rs`) when building.
2. Execute the script to generate a new version `generated.rs` (and `lib.rs`), then publish this version `*.rs` to `crates.io`.

Solution 1 (current implementation) and Solution 2 (this PR) have the same goal, but Solution 2 is more convenient for Rust users (Rust users will not install `witc`).

This is an example use case for Solution 2: https://github.com/bytecodealliance/wasi-nn/tree/main/rust

**Comment by dannypsnl** [comment]
> When I use the opencvmini crate version v0.1.0, I still can use the old version wit_v1 definition to build a rust program.

Why is this a problem? You're using different version and get different interface. Do you understand the out of sync is a maintaining issue?

Another repository use a way doesn't mean it's perfect for all repositories, focus on the point: I already say way 2 can make unacceptable situation, you need to prove way 2 can prevent it. Or we cannot merge the PR.

**Comment by yanghaku** [comment]
Hi @dannypsnl , sorry I cannot understand what out of sync is in your theory. 

The `.wit` file is the source file, and the `generated.rs` is the release file. There is a one-to-one correspondence between the source file's versions and the release file's versions.  Why ```If one update .wit definition and didn't update the generated file``` happened? Why "execute the script to update release file before publishing the library to crates.io" is a wrong assumption? Why not update the release files before publishing the new release? Users just download the release file on crates.io instead of Github, I don't think way 2 will cause out-of-sync.

And as a library user, I just want to download the release output (generated rust files). I don't want to download so many files to install `witc` when building, which is too complicated, and also consumes network, storage, and time. I would like to ask why software such as WasmEdge attaches pre-built binaries in the release, and why they do not say that "we have building scripts, you can build binaries from the source file in your computer by yourself."

**Comment by yanghaku** [comment]
I will close this PR, but I still think that `witc` dependency in this library is too inconvenient for users, Thanks.

**Comment by dannypsnl** [comment]
Because whom run script is a human, why won't a developer mistakenly forget to run build script and we also didn’t find out? If that happens, maintainers have to use more time to fix this mistake.

**Comment by yanghaku** [comment]
What does this have to do with developers running scripts? Developers do not need to execute scripts. As long as the owner runs this script before publishing the new release to `crates.io`. 

Note that **only the owner** [can publish the release to `crates.io`](https://doc.rust-lang.org/cargo/reference/publishing.html#cargo-owner), the developers cannot do it.

The workflow:
1. Developer 1 updates the `.wit`, **does not need to** update generated rust files.
2. Developer 2 updates the `.wit`, **does not need to** update generated rust files.
3. Developers 3,4,.....,n update the `.wit`.
4. Owner runs the script to generate the rust files, then publishes a new release to `crates.io`.
5. Users download the newer generated rust file from `crates.io`.

The owner can write a script to publish, like this: ```bash scripts/regenerate-bindings-from-wit.sh && cargo publish```. 
If the owner forgot to update generated files, he can also [delete this release version in crates](https://doc.rust-lang.org/cargo/reference/publishing.html#cargo-yank), which won't take long. So it's easy to maintain for owners and developers.

**Comment by dannypsnl** [comment]
Consider in `.wit` has a definition `f : a ->b` gets updated and became `f : c -> b`, if I didn't generate the file, don't it collect a list of in-consist signature? If I only generate file at before publish, I have to fix all of them at once, I have to use more time to fix this instead of current approach. How does it be easy for maintainer?

**Comment by yanghaku** [comment]
Why do you only generate files before publishing? I say that developers do not need to update generated files not meaning developers cannot update generated files.
In the current approach, when developers update `.wit`, if someone wants to view the changes in the generated file, he can pull and then run cargo to generate. In the approach of this PR, if someone wants to view the changes in the generated file, he can pull and then run the script to generate. These are no different, I think.

**Comment by hydai** [comment]
I found some examples and documents.

Take a famous project as an example, [protobuf-codegen](https://docs.rs/protobuf-codegen/3.2.0/protobuf_codegen/#how-to-use-protoc-gen-rust). It asks users to install `protoc` first.

According to the [Build script examples from the rust doc](https://doc.rust-lang.org/cargo/reference/build-script-examples.html#code-generation), the generated files should be put inside the `OUT_DIR` folder and should not change files in the `src`. 

There are two ways if users don't want to install a third-party binary and execute it in the `build.rs`:

1. [Create a standalone crate that only contains the generated files like winapi-rs](https://github.com/retep998/winapi-rs).
2. [Write a pure rust implementation of the generator such as rust-protobuf](https://github.com/stepancheg/rust-protobuf/)

For the above reason, I will choose to keep the witc dependency.

And let's provide a clear section in this repo about how to install `witc` instead. cc @dannypsnl

**Comment by yanghaku** [comment]
Yes, there are many famous code generators that are used in rust crates, such as `protoc(*.proto`), `flatc(*.fbs`), and `libclang (*.h) (use rust bindgen crate)`, etc. Almost every developer has installed these, and these tools are widely used and easy to install, such as using `apt`, `pacman`, `rpm`, or downloading binary releases directly. 
But `witc` is not now (it may need a little time), I cannot search this command on Google/Bing and even I cannot see it on the GitHub search page [1](https://github.com/search?q=witc&type=repositories&p=1) and search page [2](https://github.com/search?q=witc&type=repositories&p=2) when I tried this library. After I get the `witc` GitHub repo, I must install the Haskell toolchain to build it from the source, which is inconvenient. And there is no `witc` Rust implementation as a cargo dev-dependency.

If we treat this repository as a Rust template project instead of a Rust project and treat the repository's output release as a Rust crate,  then generated code can be put in the `src` directory and it does not need `build.rs`.

This is just my opinion, how to do it is up to you, thanks for your discussion about it  @dannypsnl  @hydai.

**Pull request closed without merging**
